import {
  bigint,
  char,
  customType,
  index,
  integer,
  numeric,
  pgSchema,
  text,
  timestamp,
  unique,
  uuid,
} from "drizzle-orm/pg-core";
import { sql } from "drizzle-orm";
import { estateCase } from "./estate.js";
import { user } from "./auth.js";

/**
 * The document library and the ingestion pipeline.
 *
 * Mirrors migrations 0021/0022. The idea that shapes it: **the original is the only thing
 * that is not derived.** `documentBlob` holds the bytes and cannot be updated; page text,
 * chunks and any eventual embedding are products of those bytes and can be thrown away
 * and rebuilt. Every derived row records the method that produced it and the confidence
 * of that method, so a passage read by OCR is never presented as though it had been read
 * off the file.
 *
 * And: **nothing says a file is clean unless a scanner said so.** A document starts
 * `quarantined`; the only routes out are a scanner's verdict or a named person's
 * deliberate, reasoned release, which records `released_unscanned` permanently.
 */

export const librarySchema = pgSchema("library");

/** PGlite and node-postgres both hand back `bytea` as a Uint8Array. */
const bytea = customType<{ data: Uint8Array; driverData: Uint8Array }>({
  dataType() {
    return "bytea";
  },
});

/** `tsvector`, which Drizzle has no builtin for. Generated by the database. */
const tsvector = customType<{ data: string; driverData: string }>({
  dataType() {
    return "tsvector";
  },
});

export const document = librarySchema.table(
  "document",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    documentNo: text("document_no").notNull().unique(),
    title: text("title").notNull(),
    /** The name the file arrived under. Part of its provenance, and fixed. */
    originalFilename: text("original_filename").notNull(),
    mediaType: text("media_type").notNull(),
    byteSize: bigint("byte_size", { mode: "number" }).notNull(),
    /** Computed from the bytes received, before anything else touched them. */
    sha256: char("sha256", { length: 64 }).notNull(),
    /** Set when the document belongs to a matter, which is how access is decided. */
    caseId: uuid("case_id").references(() => estateCase.id),
    /** internal | client | restricted */
    confidentiality: text("confidentiality").notNull().default("internal"),

    /** A guess from the filename, never treated as the answer. */
    suggestedKind: text("suggested_kind"),
    suggestedConfidence: numeric("suggested_confidence", { precision: 5, scale: 4 }),
    /** What a person says it is. */
    kind: text("kind"),
    /** rule | person — which of the two is speaking. */
    classifiedBy: text("classified_by"),
    classifiedAt: timestamp("classified_at", { withTimezone: true }),

    /** quarantined | clean | infected | released_unscanned | scan_failed */
    scanStatus: text("scan_status").notNull().default("quarantined"),
    scanner: text("scanner"),
    scannerVersion: text("scanner_version"),
    scannedAt: timestamp("scanned_at", { withTimezone: true }),
    scanDetail: text("scan_detail"),
    releasedBy: uuid("released_by").references(() => user.id),
    releasedAt: timestamp("released_at", { withTimezone: true }),
    releaseReason: text("release_reason"),

    /** pending | extracted | needs_ocr | unsupported | failed */
    extractionStatus: text("extraction_status").notNull().default("pending"),
    extractionMethod: text("extraction_method"),
    extractionConfidence: numeric("extraction_confidence", { precision: 5, scale: 4 }),
    extractionDetail: text("extraction_detail"),
    pageCount: integer("page_count"),
    textChars: integer("text_chars"),
    extractedAt: timestamp("extracted_at", { withTimezone: true }),

    chunkCount: integer("chunk_count").notNull().default(0),
    indexedAt: timestamp("indexed_at", { withTimezone: true }),
    /** not_requested | not_configured | embedded | failed */
    embeddingStatus: text("embedding_status").notNull().default("not_requested"),
    embeddingModel: text("embedding_model"),
    embeddedAt: timestamp("embedded_at", { withTimezone: true }),
    embeddingDetail: text("embedding_detail"),

    retentionNote: text("retention_note"),
    notes: text("notes"),
    archivedAt: timestamp("archived_at", { withTimezone: true }),
    archivedBy: uuid("archived_by").references(() => user.id),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
    createdBy: uuid("created_by")
      .notNull()
      .references(() => user.id),
    updatedBy: uuid("updated_by").references(() => user.id),
  },
  (table) => ({
    byCase: index("document_case_idx").on(table.caseId),
    bySha: index("document_sha_idx").on(table.sha256),
    byScan: index("document_scan_idx").on(table.scanStatus),
  }),
);

/**
 * The original, byte for byte. No UPDATE, ever (trigger).
 *
 * In the database rather than on a disk so that a backup restores the file and the row
 * describing it together. Everything else in this schema can be rebuilt from here.
 */
export const documentBlob = librarySchema.table("document_blob", {
  documentId: uuid("document_id")
    .primaryKey()
    .references(() => document.id, { onDelete: "cascade" }),
  content: bytea("content").notNull(),
  byteSize: bigint("byte_size", { mode: "number" }).notNull(),
  sha256: char("sha256", { length: 64 }).notNull(),
  storedAt: timestamp("stored_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Page text, where the extraction method produces pages.
 *
 * Separate from the chunks because a page is a fact about the document and a chunk is a
 * choice about how to split it — rechunking must not require re-extraction.
 */
export const documentPage = librarySchema.table(
  "document_page",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => document.id, { onDelete: "cascade" }),
    pageNo: integer("page_no").notNull(),
    text: text("text").notNull(),
    /** plain_text | docx_xml | ocr | manual */
    method: text("method").notNull(),
    /** Null when the method states no confidence. Never invented. */
    confidence: numeric("confidence", { precision: 5, scale: 4 }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    unique: unique("document_page_unique").on(table.documentId, table.pageNo),
  }),
);

/**
 * What retrieval searches.
 *
 * Two generated tsvectors: `english`, which stems, and `simple`, which does not.
 * PostgreSQL ships no Malay configuration, so Malay text is matched on exact tokens while
 * English text also benefits from stemming; a query runs against both.
 *
 * `embedding` is `real[]` rather than a pgvector column — the extension is unavailable in
 * PGlite, and a nearest-neighbour index that is really a sequential scan would be a
 * performance lie. It is null everywhere until a model is configured (Q-AI-1).
 */
export const chunk = librarySchema.table(
  "chunk",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => document.id, { onDelete: "cascade" }),
    ordinal: integer("ordinal").notNull(),
    text: text("text").notNull(),
    pageFrom: integer("page_from"),
    pageTo: integer("page_to"),
    /** Offsets into the document's combined extracted text, so a hit is locatable. */
    charFrom: integer("char_from").notNull(),
    charTo: integer("char_to").notNull(),
    tokenEstimate: integer("token_estimate").notNull(),
    method: text("method").notNull(),
    confidence: numeric("confidence", { precision: 5, scale: 4 }),
    tsvEn: tsvector("tsv_en"),
    tsvSimple: tsvector("tsv_simple"),
    embedding: numeric("embedding").array(),
    embeddingModel: text("embedding_model"),
    embeddedAt: timestamp("embedded_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    ordinalUnique: unique("chunk_ordinal_unique").on(table.documentId, table.ordinal),
    byDocument: index("chunk_document_idx").on(table.documentId, table.ordinal),
  }),
);

/**
 * The pipeline's own record, append-only.
 *
 * Not the audit trail: this answers "what happened to this file, in order, and why did it
 * stop". When somebody asks why a document is not searchable, this is the answer.
 */
export const ingestionEvent = librarySchema.table(
  "ingestion_event",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    documentId: uuid("document_id")
      .notNull()
      .references(() => document.id, { onDelete: "cascade" }),
    /** registered | scanned | classified | extracted | chunked | embedded | released | archived | rebuilt */
    stage: text("stage").notNull(),
    /** ok | blocked | failed | skipped */
    outcome: text("outcome").notNull(),
    detail: text("detail").notNull(),
    actorUserId: uuid("actor_user_id").references(() => user.id),
    actorLabel: text("actor_label"),
    occurredAt: timestamp("occurred_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => ({
    byDocument: index("ingestion_event_document_idx").on(table.documentId, table.occurredAt),
  }),
);

/** Kept so the generated-column expressions stay visible beside the table. */
export const LIBRARY_TSVECTOR_SQL = {
  english: sql`to_tsvector('english', coalesce(text, ''))`,
  simple: sql`to_tsvector('simple', coalesce(text, ''))`,
};
